Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [5]:
pip install numpy

     ---------------------------------------- 15.6/15.6 MB 4.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:


# Program to distinguish Array Indexing and Fancy Indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Array indexing
print("Array Indexing:")
print(arr[0])  # Output: 10
print(arr[3])  # Output: 40
print("")

# Fancy indexing
print("Fancy Indexing:")
indices = [0, 2, 4]
print(arr[[0, 2, 4]])  # Output: [10, 30, 50]



Array Indexing:
10
40

Fancy Indexing:
[10 30 50]


Execute the 2D array Slicing.

In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]



Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [12]:
import numpy as np

# Create a 5-dimensional array with shape (2, 3, 4, 5, 6)
arr = np.array([1, 2, 3, 4, 5, 6], ndmin=5)

print(arr)
print(f"Shape: {arr.shape}")


[[[[[1 2 3 4 5 6]]]]]
Shape: (1, 1, 1, 1, 6)


In [ ]:
Q4. Reshape the array from 1-D to 2-D array.

In [13]:
import numpy as np

# Create a 1-D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to 2-D with shape (2, 3)
arr2d = arr1d.reshape(2, 3)

print(arr2d)
print(f"Shape: {arr2d.shape}")


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking arrays along a new axis
result = np.stack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking arrays horizontally
result = np.hstack((a, b))

print(result)


[1 2 3 4 5 6]


In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking arrays vertically
result = np.vstack((a, b))

print(result)


[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking arrays depth-wise
result = np.dstack((a, b))

print(result)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Q6. Perform the searchsort method in Numpy array.

In [20]:
import numpy as np
arr = np.array([1, 2, 4, 5, 6, 8, 9])
index = np.searchsorted(arr, 6)
print("Index to insert 6:", index)
values = np.array([3, 7, 10])
indices = np.searchsorted(arr, values)
print("Indices to insert values:", indices)






Index to insert 6: 4
Indices to insert values: [2 5 7]


Q7. Create Numpy Structured array using your domain features.

In [21]:
import numpy as np


a = np.array([('Dr Kim', 5, 21000.0), (' Dr Sam', 4, 3000.0), ('Dr John', 10, 4000.0)],
       dtype=[('name', (np.str_, 10)), ('experience', np.int32), ('fee', np.float64)])

print(a)

[('Dr Kim',  5, 21000.) (' Dr Sam',  4,  3000.) ('Dr John', 10,  4000.)]


Q8. Create Data frame using List and Dictionary.

In [23]:
pip install pandas

     ---------------------------------------- 11.1/11.1 MB 2.1 MB/s eta 0:00:00
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     -------------------------------------- 502.5/502.5 kB 1.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [24]:
import pandas as pd
data = [
    {'name': 'John', 'age': 30},
    {'name': 'Mary', 'age': 25},
    {'name': 'Bob', 'age': 40}
]
df = pd.DataFrame(data)
print(df)

   name  age
0  John   30
1  Mary   25
2   Bob   40


Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.

In [2]:
import pandas as pd
import numpy as np
domainDF = pd.DataFrame({"patients":[1,2,3,4],"tretment Price":[500,720,900,1180],"patient Email":[np.nan,np.nan,np.nan, 0]})
print(domainDF)
print("\nIs Null")
print(domainDF.isnull())
print("\nNot Null")
print(domainDF.notnull())
print("\nDrop Null")
print(domainDF.dropna())
print("\nFill Null")
print(domainDF.fillna(0))
print("\nReplace")
print(domainDF.replace(np.nan,0))
print("\nInterpolate")
print(domainDF.interpolate(axis=1))

   patients  tretment Price  patient Email
0         1             500            NaN
1         2             720            NaN
2         3             900            NaN
3         4            1180            0.0

Is Null
   patients  tretment Price  patient Email
0     False           False           True
1     False           False           True
2     False           False           True
3     False           False          False

Not Null
   patients  tretment Price  patient Email
0      True            True          False
1      True            True          False
2      True            True          False
3      True            True           True

Drop Null
   patients  tretment Price  patient Email
3         4            1180            0.0

Fill Null
   patients  tretment Price  patient Email
0         1             500            0.0
1         2             720            0.0
2         3             900            0.0
3         4            1180            0.0

Replace
   p

Q10. Perform the Hierarchical Indexing in the above created dataset.

In [5]:
print("Hierarchical Indexing")
domainDF2 = domainDF.set_index(['tretment Price'])
domainDF2.sort_index()
print(domainDF2)
domainDF2.loc[[900]]

Hierarchical Indexing
                patients  patient Email
tretment Price                         
500                    1            NaN
720                    2            NaN
900                    3            NaN
1180                   4            0.0


patients  patient Email
tretment Price                         
900                    3            NaN